FROM nginx:1.17.5-alpine

# remove default config
RUN rm /etc/nginx/nginx.conf
# place my config here as per doc mention
COPY nginx.conf /etc/nginx/nginx.conf

# CMD ["nginx", "-g", "daemon off;", "$@"]