FROM tiangolo/uwsgi-nginx-flask:python3.7

ENV PATH=$PATH:/usr/local/bin
ENV APP_HOME /app

RUN mkdir -p $APP_HOME 
WORKDIR $APP_HOME

COPY uwsgi.ini uwsgi.ini
COPY nginx.conf nginx.conf
COPY models models
COPY init.py init.py
COPY utils.py utils.py
COPY app.py app.py
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt